#!/bin/bash
# change this file to your needs

echo "Adding some modules"

modules add gcc

echo "#################"
echo "    COMPILING    "
echo "#################"

g++ -Wall -std=c++17 -O3 src/*.cpp -o network

echo "#################"
echo "     RUNNING     "
echo "#################"

./network
