#!/bin/bash
# change this file to your needs

echo "Adding some modules"

modules add gcc

echo "#################"
echo "    COMPILING    "
echo "#################"

# g++ -Wall -std=c++17 -O3 src/main.cpp src/file2 -o network

echo "#################"
echo "     RUNNING     "
echo "#################"

# ./network
